# Configuration for release-plz (https://release-plz.dev).

[workspace]
git_tag_name = "v{{ version }}"
git_release_name = "{{ version }}"

[changelog]
commit_parsers = [
    { footer = "^changelog: ?ignore", skip = true },
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^refactor", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^removed", group = "removed" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = ".*", group = "other" },
]

[[package]]
name = "merge-lab"
release = false
publish = false

[[package]]
name = "xtask"
release = false
publish = false
